dist:
  name: otelcol-dev
  description: Basic OpenTelemetry collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.85.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.85.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.85.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.85.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.85.0

connectors:
  - gomod: github.com/CarnegieMellon-PlantD/plantdconnector v0.85.0
replaces:
  # a list of "replaces" directives that will be part of the resulting go.mod

  # This replace statement is necessary since the newly added component is not found/published to GitHub yet. Replace references to GitHub path with the local path
  - github.com/CarnegieMellon-PlantD/plantdconnector => C:/CMU/DPWT/plantdconnector
